version: '3.7'
services:
  cypress:
    image: cypress
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./dockerReports/:/app/cypress/results
      - ./dockerReports/:/app/mochawesome-report

